projects:
  rustc:
    github_repo: https://github.com/teenygrad/rust.git
    branch: main
    prompt_dir: .ai/prompts
    commands:
      plan:
        queue: rust-plan
        cmd: "agent plan project=rust agent=claude"
      execute:
        queue: rust-execute
        cmd: "agent execute project=rust agent=claude"
